theme:
  name: material
  features:
  - content.code.copy
site_name: e-footprint documentation

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

docs_dir: docs_sources/mkdocs_sourcefiles

site_dir: docs

nav:
- Introduction: index.md
- Tutorial: tutorial.md
- Explanation:
  - Explanation overview: explanation_overview.md
  - e-footprint scope: efootprint_scope.md
  - Why e-footprint ?: why_efootprint.md
  - How to get started: get_started.md
  - The e-footprint methodology: methodology.md
  - e-footprint design choices deep dive: design_deep_dive.md
- How-to guides:
    - How to model a machine learning workflow: machine_learning_workflow.md
    - How to model a database: database_modeling.md
    - How to model the evolution of a system across time: evolution_across_time.md
    - How to model server to server interaction: server_to_server_interaction.md
- e-footprint objects reference:
  - How to read the object reference: object_reference.md
  - Hardware:
      - Servers:
          - Autoscaling: Autoscaling.md
          - On Premise: OnPremise.md
          - Serverless: Serverless.md
      - Hardware: Hardware.md
      - Network: Network.md
      - Storage: Storage.md
  - Usage:
      - UsagePattern: UsagePattern.md
      - UserJourney: UserJourney.md
      - UserJourneyStep: UserJourneyStep.md
      - Job: Job.md
  - Service: Service.md
  - System: System.md
  - Country: Country.md
- e-footprint builders: builders.md
- FAQ:
    - What about best practices ?: best_practices.md
    - What about measurement tools ?: measurement_tools.md
    - What about the build process of the service ?: build_process.md
    - Why only CO2 ?: only_CO2.md
- External links: links.md
- Changelog: Changelog.md